### ISSUE TITLE
Next Slide feature is broken with new installer

### ISSUE THREAD

**Issue by tamarahills** [tamarahills/foxycli#54]
When you say 

"Hey Foxy Next slide"
"Hey Foxy, Go forward"

It should send a right arrow keystroke.  If you are on a google slides presentation, this will advance the slide.

If you say:
"Hey Foxy, Go back"
"Hey Foxy, Previous slide"

This should send a left arrow keystroke.  If you are on a google slides presentation, it should go back one slide.  

Note that this only works when you have the google slide selected in the window.

This exec's a new node process, so, I'm betting that the new OS level process management is the problem here.

**Comment by IlyaKnysh** [comment]
Current implementation run command via `spawn` from child process. The command is use `/Application/FoxyExtension` path. So Nikolay suggests to use `robot.js` directly without process spawning. He will add PR ASAP.
